DROP TABLE if exists hits;

CREATE  table If not exists hits(
id integer generated by default as identity primary key,
app varchar(100) not null,
uri varchar(100) not null,
ip varchar(100) not null,
timestamp timestamp without time zone not null);


