DROP TABLE if exists events_compilations;
DROP TABLE if exists requests;
DROP TABLE if exists compilations;
DROP TABLE if exists events;
DROP TABLE if exists categories;
DROP TABLE if exists users;

CREATE TABLE If not exists users (
id integer generated by default as identity primary key,
name varchar (250) not null,
email varchar(254) not null);

CREATE TABLE If not exists categories (
id integer generated by default as identity primary key,
name varchar(50) not null);

CREATE TABLE if not exists compilations (
id integer generated by default as identity primary key,
title varchar (50) not null,
pinned boolean);

CREATE TABLE if not exists events(
id integer generated by default as identity primary key,
annotation varchar(2000) not null,
category_id integer references categories(id),
created_on timestamp,
description varchar(7000),
event_date timestamp not null,
initiator_id integer not null references users(id),
location_lat numeric(6) not null,
location_lon numeric(6) not null,
paid boolean not null,
participant_limit integer not null,
published_on timestamp,
request_moderation boolean,
state varchar(20),
title varchar(120) not null);

CREATE TABLE if not exists events_compilations (
event_id integer not null references events(id),
comp_id integer not null references compilations(id));

CREATE TABLE if not exists requests (
id integer generated by default as identity primary key,
event integer not null references events(id),
requester integer not null references users(id),
created timestamp,
status varchar not null);