DROP TABLE events_compilations;
DROP TABLE requests;
DROP TABLE compilations;
DROP TABLE events;
DROP TABLE categories;
DROP TABLE users;

CREATE TABLE If not exists users (
id integer generated by default as identity primary key,
name varchar (50) not null,
email varchar(50) not null);

CREATE TABLE If not exists categories (
id integer generated by default as identity primary key,
name varchar(50) not null);

CREATE TABLE if not exists compilations (
id integer generated by default as identity primary key,
title varchar (50) not null,
pinned boolean not null);

CREATE TABLE if not exists events(
id integer generated by default as identity primary key,
annotation varchar(200) not null,
category_id integer references categories(id),
created_on timestamp,
description varchar(500),
event_date timestamp not null,
initiator_id integer not null references users(id),
paid boolean not null,
participant_limit integer not null,
published_on timestamp,
request_moderation boolean,
state varchar(20),
title varchar(100) not null);

CREATE TABLE if not exists events_compilations (
event_id integer not null references events(id),
comp_id integer not null references compilations(id));

CREATE TABLE if not exists requests ();